#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/reflect
)

set( PRIVATE_GENERATED_HEADERS
src/reflect/_MulleWebClient-import-private.h
src/reflect/_MulleWebClient-include-private.h
)

set( PRIVATE_HEADERS
src/import-private.h
)

set( PUBLIC_GENERATED_HEADERS
src/reflect/_MulleWebClient-import.h
src/reflect/_MulleWebClient-include.h
)

set( PUBLIC_HEADERS
src/MulleCurl+JSON.h
src/MulleCurl+NSURL.h
src/MulleHTTPHeaderParser+MulleCurlParser.h
src/MulleJSMNParser+MulleCurlParser.h
src/MulleObjCLoader+MulleWebClient.h
src/MulleWebClient.h
src/import.h
)

