/*
*   This file will be regenerated by `mulle-sde reflect` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _MulleWebClient_import_h__
#define _MulleWebClient_import_h__

// How to tweak the following MulleCurl #import
//    remove:          `mulle-sourcetree mark MulleCurl no-header`
//    rename:          `mulle-sourcetree mark MulleCurl set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark MulleCurl [no-]import`
//    toggle public:   `mulle-sourcetree mark MulleCurl [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleCurl [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleCurl no-os-<osname>`
# import <MulleCurl/MulleCurl.h>   // MulleCurl

// How to tweak the following MulleObjCInetFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCInetFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCInetFoundation set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark MulleObjCInetFoundation [no-]import`
//    toggle public:   `mulle-sourcetree mark MulleObjCInetFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCInetFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCInetFoundation no-os-<osname>`
# import <MulleObjCInetFoundation/MulleObjCInetFoundation.h>   // MulleObjCInetFoundation

// How to tweak the following MulleObjCJSMNFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCJSMNFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCJSMNFoundation set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark MulleObjCJSMNFoundation [no-]import`
//    toggle public:   `mulle-sourcetree mark MulleObjCJSMNFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCJSMNFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCJSMNFoundation no-os-<osname>`
# import <MulleObjCJSMNFoundation/MulleObjCJSMNFoundation.h>   // MulleObjCJSMNFoundation

// How to tweak the following MulleObjCHTTPFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCHTTPFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCHTTPFoundation set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark MulleObjCHTTPFoundation [no-]import`
//    toggle public:   `mulle-sourcetree mark MulleObjCHTTPFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCHTTPFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCHTTPFoundation no-os-<osname>`
# import <MulleObjCHTTPFoundation/MulleObjCHTTPFoundation.h>   // MulleObjCHTTPFoundation

#include "_MulleWebClient-include.h"


#endif
