/*
 *   This file will be regenerated by `mulle-bash`.
 *   Any edits will be lost.
 */
#if defined( MULLE_CURL_VERSION)
# if MULLE_CURL_VERSION < ((0 << 20) | (18 << 8) | 0)
#  error "MulleCurl is too old"
# endif
# if MULLE_CURL_VERSION >= ((0 << 20) | (19 << 8) | 0)
#  error "MulleCurl is too new"
# endif
#endif

#if defined( MULLE_OBJC_HTTP_FOUNDATION_VERSION)
# if MULLE_OBJC_HTTP_FOUNDATION_VERSION < ((0 << 20) | (18 << 8) | 4)
#  error "MulleObjCHTTPFoundation is too old"
# endif
# if MULLE_OBJC_HTTP_FOUNDATION_VERSION >= ((0 << 20) | (19 << 8) | 0)
#  error "MulleObjCHTTPFoundation is too new"
# endif
#endif

#if defined( MULLE_OBJC_INET_FOUNDATION_VERSION)
# if MULLE_OBJC_INET_FOUNDATION_VERSION < ((0 << 20) | (18 << 8) | 4)
#  error "MulleObjCInetFoundation is too old"
# endif
# if MULLE_OBJC_INET_FOUNDATION_VERSION >= ((0 << 20) | (19 << 8) | 0)
#  error "MulleObjCInetFoundation is too new"
# endif
#endif

#if defined( MULLE_OBJC_JSMN_FOUNDATION_VERSION)
# if MULLE_OBJC_JSMN_FOUNDATION_VERSION < ((0 << 20) | (18 << 8) | 4)
#  error "MulleObjCJSMNFoundation is too old"
# endif
# if MULLE_OBJC_JSMN_FOUNDATION_VERSION >= ((0 << 20) | (19 << 8) | 0)
#  error "MulleObjCJSMNFoundation is too new"
# endif
#endif
