/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use 3EEF6B21-F716-4F6D-8439-E0C6B0F31F1A instead of MulleCurl if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleCurl no-header`
//    rename:             `mulle-sde dependency|library set MulleCurl include whatever.h`
//    reorder:            `mulle-sourcetree move MulleCurl <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleCurl [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleCurl [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleCurl [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleCurl no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#import <MulleCurl/MulleCurl.h>   // MulleCurl

// You can tweak the following #import with these commands.
// (Use 96432DD6-5F89-4189-AEFD-87300A0D1BE7 instead of MulleObjCInetFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCInetFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCInetFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCInetFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCInetFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCInetFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCInetFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCInetFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#import <MulleObjCInetFoundation/MulleObjCInetFoundation.h>   // MulleObjCInetFoundation

// You can tweak the following #import with these commands.
// (Use 826EAAA9-2883-4BB3-B7BA-00AE3E9970FD instead of MulleObjCJSMNFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCJSMNFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCJSMNFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCJSMNFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCJSMNFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCJSMNFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCJSMNFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCJSMNFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#import <MulleObjCJSMNFoundation/MulleObjCJSMNFoundation.h>   // MulleObjCJSMNFoundation

// You can tweak the following #import with these commands.
// (Use 3d1dad4d-4759-4c1c-9349-ee9751b64f9c instead of MulleObjCHTTPFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCHTTPFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCHTTPFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCHTTPFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCHTTPFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCHTTPFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCHTTPFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCHTTPFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#import <MulleObjCHTTPFoundation/MulleObjCHTTPFoundation.h>   // MulleObjCHTTPFoundation

#ifdef __has_include
# if __has_include( "_MulleWebClient-include.h")
#  include "_MulleWebClient-include.h"
# endif
#endif

