      { @selector( MulleObjCLoader), @selector( MulleCurl) },      // 47a9beb6;MulleObjCLoader;9714448a;MulleCurl
      { @selector( MulleObjCLoader), @selector( MulleObjCHTTPFoundation) },      // 47a9beb6;MulleObjCLoader;457d3115;MulleObjCHTTPFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCInetFoundation) },      // 47a9beb6;MulleObjCLoader;088ec1b3;MulleObjCInetFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCJSMNFoundation) },      // 47a9beb6;MulleObjCLoader;383fe71a;MulleObjCJSMNFoundation
      { @selector( MulleCurl), @selector( JSON) },      // 9714448a;MulleCurl;fbd7fc3d;JSON
      { @selector( MulleCurl), @selector( NSURL) },      // 9714448a;MulleCurl;6b1e8f73;NSURL
      { @selector( MulleHTTPHeaderParser), @selector( MulleCurlParser) },      // 33ba7405;MulleHTTPHeaderParser;3ef706fe;MulleCurlParser
      { @selector( MulleJSMNParser), @selector( MulleCurlParser) },      // 11d4e75e;MulleJSMNParser;3ef706fe;MulleCurlParser
