#
# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
)

set( PRIVATE_HEADERS
src/import-private.h
)

set( PUBLIC_HEADERS
src/MulleCurl+JSON.h
src/MulleCurl+NSURL.h
src/MulleHTTPHeaderParser+MulleCurlParser.h
src/MulleJSMNParser+MulleCurlParser.h
src/MulleObjCLoader+MulleWebClient.h
src/MulleWebClient.h
src/import.h
)

