#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/MulleCurl+JSON.m
src/MulleCurl+NSURL.m
src/MulleHTTPHeaderParser+MulleCurlParser.m
src/MulleJSMNParser+MulleCurlParser.m
src/MulleWebClient.m
)

set( STAGE2_SOURCES
src/MulleObjCLoader+MulleWebClient.m
)
